---
- hosts: nxos
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
    ansible_network_os: cisco.nxos.nxos
  tasks:
  - name: "Fetch interface state and parse with pyats"
    ansible.utils.cli_parse:
      command: show interface loopback 0-1
      parser:
        name: ansible.netcommon.pyats
    register: nxos_pyats_show_interface

  - name: print structured interface state data
    ansible.builtin.debug:
      msg: "{{ nxos_pyats_show_interface['parsed'] }}"

  - name: validate interface for admin state
    ansible.utils.validate:
      data: "{{ nxos_pyats_show_interface['parsed'] }}"
      criteria:
        - "{{ lookup('file',  './validate/criterias/nxos_show_interface_admin_criteria.json') | from_json }}"
      engine: ansible.utils.jsonschema
    ignore_errors: true
    register: result

  - name: print the interface names that does not satisfy the desired state
    ansible.builtin.debug:
      msg: "{{ item['data_path'].split('.')[0] }}"
    loop: "{{ result['errors'] }}"
